# Generated by Django 4.2 on 2023-04-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.CharField(default=None, max_length=10000),
        ),
        migrations.DeleteModel(
            name='ArticleText',
        ),
    ]
